name: Generate Comfy Image

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt for the image"
        required: false
        default: >
          SportSync AI brand visual — elite sprinter exploding off the blocks,
          dramatic rim light, motion trails, subtle holographic sports analytics
          overlay (heart rate 168, speed 10.2 m/s), matte-black background,
          neon cyan and electric purple accents, ultra-detailed, cinematic,
          high contrast, clean composition

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate image via RunPod
        env:
          RUNPOD_ENDPOINT_ID: ${{ secrets.RUNPOD_ENDPOINT_ID }}
          RUNPOD_API_KEY:    ${{ secrets.RUNPOD_API_KEY }}
        run: |
          mkdir -p outputs
          python tools/comfy_runsync_save_image.py \
            --workflow tools/workflows/flux1_text2img.json \
            --prompt "${{ inputs.prompt }}" \
            --out "outputs/brand_sprinter_${{ github.run_number }}.png"

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: brand_image
          path: outputs/*.png
          if-no-files-found: error

      - name: List outputs
        run: ls -lh outputs
